nodeLinker: node-modules

yarnPath: .yarn/releases/yarn-3.0.2.cjs

packageExtensions:
  next-pwa@*:
    dependencies:
      "@babel/core": "*"
      webpack: "*"
  "@typescript-eslint/eslint-plugin@*":
    dependencies:
      "@typescript-eslint/parser": "*"

